# This config file is meant for settings that affect your whole activity list, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: BetterMTL Activity
  fr: Activité MieuxMTL

# What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label:
  en: Activity
  fr: Activité

description:
  en: Montrealers team up better city
  fr: Les Montréalais se équipent meilleure ville

index:
  en:
  fr: accueil.html

feed:
  en: /feed.xml
  fr: /flux.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bettermtl.com/" # the base hostname & protocol for your site

timezone: America/Montreal

author: Paul Cuciureanu
twitter_username: BetterMTL
github_username:  bettermtl
company_name: BetterMTL

# Build settings
markdown: kramdown

# Show future posts for future events.
future: true

permalink: /event/:title.html
