# This config file is meant for settings that affect your whole activity list, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

collections:
  locations:
    output: true
    permalink: /l/:title:output_ext
  network:
    output: true
    permalink: /n/:name:output_ext
  activities:
    output: true
    permalink: /a/:title:output_ext

lang:
  primary: fr
  secondary: en

defaults:
  - scope:
      path: ""
    values:
      lang: "fr"
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: locations
    values:
      layout: location
  - scope:
      path: ""
      type: network
    values:
      layout: node

navigation:
  fr:
  - title: Activité
    url: /
  - title: Réseau
    url: /reseau/
  - title: Endroits
    url: /endroits/
  - title: Blogue
    url: /blogue/
  - title: À propos
    url: /a-propos/
  - title: Publier
    url: /creer/
  en:
  - title: Activity
    url: /welcome/
  - title: Network
    url: /network/
  - title: Locations
    url: /locations/
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Create
    url: /create/

# Site settings
title:
  en: BetterMTL
  fr: CapMTL

description:
  en: BetterMTL is free and open-source. <br/> Run by <a href='https://github.com/bettermtl/bettermtl.github.io/graphs/contributors'>contributors</a>.
  fr: CapMTL est un logiciel libre. <br/> Géré par <a href='https://github.com/bettermtl/bettermtl.github.io/graphs/contributors'>contributeurs</a>.

index:
  en: welcome
  fr:

feed:
  en: /feed.xml
  fr: /flux.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bettermtl.com/" # the base hostname & protocol for your site

timezone: America/Montreal

author: Paul Cuciureanu
facebook_username: bettermtl
twitter_username: BetterMTL
github_username:  bettermtl
company_name: BetterMTL

# Build settings
markdown: kramdown

# Show future posts for future events.
future: true

permalink: /p/:title.html
